## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI Windows

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  ## Build Jobs ##

  build-windows-msvc15:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      cmd: |
        .github\scripts\build.ps1 "Visual Studio 15 2017 Win64" "v141"
      artifact-out: build-windows-msvc15
      artifact-path: build

  build-windows-msvc16:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      cmd: |
        .github\scripts\build.ps1 "Visual Studio 16 2019" "v142"
      artifact-out: build-windows-msvc16
      artifact-path: build

  ## Functional Test Jobs ##

  test-windows-msvc15:
    needs: build-windows-msvc15
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      cmd: |
        .github\scripts\run_tests.ps1
      artifact-in: build-windows-msvc15

  test-windows-msvc16:
    needs: build-windows-msvc16
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      cmd: |
        .github\scripts\run_tests.ps1
      artifact-in: build-windows-msvc16
